### PR TITLE
Change all references to HEP-SF to HSF

### PR DESCRIPTION
**Pull request by graeme-a-stewart**
Follows change of organisation name on GitHub

### CODE REVIEW

**Comment by graeme-a-stewart** [comment]
This is also a test of whether the pipeline all still works with the renamed organisation...

**Comment by graeme-a-stewart** [comment]
OK, looks good now. The one proofer failure was the P5 report having a wobbly (it's back now, AFAICS).

So, should we accept this PR, then rename the repo or rename the repo first? I haven't found a HOWTO for this. Maybe we just suck it and see...

**Comment by jouvin** [comment]
The P5 link seems still unreliable... May be worth to exclude from the checks... On your question, I'd say, let's merge this PR and see what happens. We can rename the repo afterwards if necessary. The only possible of the repo name not matching the organization name is that updates are not visible on the web site (and probably an error email from GitHub), so easy to check. As the old name is an alias to the new name, it's possible it will just work.

**Comment by graeme-a-stewart** [comment]
@jouvin - yeah, I would be happy to just merge this now and we see what happens. Shall I just proceed then?

**Comment by jouvin** [comment]
@graeme-a-stewart what about excluding P5 link from the checks? I think it happens regularly with this link and this is painful it triggers false errors... Apart from this detail, I'm happy to merge this PR.

**Comment by graeme-a-stewart** [comment]
The changes are not visible on the website, so shall we rename the repo and try again?

To that end, do you know who registered `hepsoftwarefoundation.org` and how it's managed?

**Comment by graeme-a-stewart** [comment]
OK,. https://www.whois.net/ say's it's Torre.

**Comment by wenaus** [comment]
Hi, yes it is CNAMEd to hep-sf.github.io, I can change it when you're ready

**Comment by jouvin** [comment]
I opened issue https://github.com/HSF/hep-sf.github.io/issues/324 to track the work to be done rather than using a closed PR...

**Pull request merged**
